services:
  - type: web
    name: auction-keeper
    env: node
    plan: free
    buildCommand: cd auction_cc/keeper && pnpm install && pnpm run build
    startCommand: cd auction_cc/keeper && pnpm start
    healthCheckPath: /health
    repo: https://github.com/your-username/your-repo-name.git
    rootDir: auction_cc/keeper
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    autoDeploy: true
    disk:
      name: auction-keeper-disk
      mountPath: /tmp
      sizeGB: 1